#!/bin/bash
set -e
POSTGRES_WORDLE_SERVER_USER_PASSWORD=$(cat $POSTGRES_WORDLE_SERVER_USER_PASSWORD_FILE)
cat $POSTGRES_ADMIN_PASSWORD_FILE | psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
	CREATE USER IF NOT EXISTS "$WORDLE_SERVER_USER_NAME" WITH PASSWORD '$POSTGRES_WORDLE_SERVER_USER_PASSWORD';
	CREATE DATABASE IF NOT EXISTS $WORDLE_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $WORDLE_DB_NAME TO "$WORDLE_SERVER_USER_NAME";
EOSQL

echo $POSTGRES_WORDLE_SERVER_USER_PASSWORD | psql -v ON_ERROR_STOP=1 -U "$WORDLE_SERVER_USER_NAME" -d $WORDLE_DB_NAME -a -f create_server_game_tables.sql
echo $POSTGRES_WORDLE_SERVER_USER_PASSWORD | psql -v ON_ERROR_STOP=1 -U "$WORDLE_SERVER_USER_NAME" -d $WORDLE_DB_NAME -a -f words.sql
