#!/bin/bash
set -e

POSTGRES_WORDLE_SERVER_USER_PASSWORD=$(cat $POSTGRES_WORDLE_SERVER_USER_PASSWORD_FILE)
POSTGRES_ADMIN_PASSWORD=$(cat $POSTGRES_ADMIN_PASSWORD_FILE)

echo password | psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
	ALTER USER "$POSTGRES_USER" WITH PASSWORD '$POSTGRES_ADMIN_PASSWORD';
EOSQL

echo $POSTGRES_ADMIN_PASSWORD | psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$WORDLE_SERVER_USER_NAME" WITH PASSWORD '$POSTGRES_WORDLE_SERVER_USER_PASSWORD';
	CREATE DATABASE "$WORDLE_DB_NAME";
	GRANT ALL PRIVILEGES ON DATABASE "$WORDLE_DB_NAME" TO "$WORDLE_SERVER_USER_NAME";
EOSQL

export PGPASSWORD="$POSTGRES_WORDLE_SERVER_USER_PASSWORD"
cat create_server_game_tables.sql | psql -v ON_ERROR_STOP=1 postgres://$WORDLE_SERVER_USER_NAME@postgres-server:5432/$WORDLE_DB_NAME
cat words.sql | psql -v ON_ERROR_STOP=1 postgres://$WORDLE_SERVER_USER_NAME@postgres-server:5432/$WORDLE_DB_NAME

